import guide as guide


residues = [
    173,
    230, 231, 232, 233,
    290, 291, 
    326,
    437
]


def exercise_12():
  aln = guide.readClustalFile('exercise7.aln', guide.Protein_wGAP)
  tree = guide.runUPGMA(aln, 'poisson')
  tree.putAlignment(aln)
  tree.parsimony()
  # print("Sequence:\n\n", sequence)
  # s = tree.strSequences()
  s = tree.strSites(residues)
  print(s)

# exercise_12()

exercise_12();


# aln = guide.readClustalFile('exercise7.aln', guide.Protein_wGAP)
# # print(aln.seqs[0])

# # s = 
# # "---MTISSAHPETDPKWWKEATIYQIYPASFKDSN-----------NDGWGDMKGIASKLEYIKGLGVDAIWISPFYDSPQDDMGYDIANYEKVWPTYGTNEDCFALIEKTHKFGMKFITDLVINHCSSEHEWFKESRSSKTNPKRDWFFWKPPKGYDDEGNPIPPNNWKSYFGGSAWTFDEKTQEFYLRLFCPRQPDLNWESEDCRKAIYESAVGYWLDHGVDGFRIDVGSLYSKVVGLPDAPITDKNSLWQSSDPLTLNGPRIHEFHQEMNRFIRNRV-KDGREIMTVGEMQHASDATKKLYTSASRCELGELFNFSHTDVGTSPLFRYNLVPAELKDWKVALAELFRYINGTDCWSTIYLENHDQPRSITRFGDDSTKNRVISGKLLSVLLVSLTGTLFIYQGQELGQINF-KNWPVEKYEDVEIRNNYKLIKEEHGEKSE---QMKKFLDGIALVSRDHARTPMPWTHEEPNAGFSG---PNAKPWFSLNESFREGINVEDEQKNPDSVLAFWRKALEFRKSHKDIAVYGYDFEFIDLDNKRLFSFTKK--Y-ENKTLFAALNFSSELLDFEIPKANSSYTLAFGNYPSDQINPSSRTLKPWEGRIYIDE--"
# # print(s[218])

# # >S.cerevisiae YIIc17_E5
# voordeckers = [173, 231, 232, 233, 234, 294, 295, 324, 437]

# voordeckers_seq = "MVSMPN---HPETEPKWWKEATVYQIYPASF----------KDSDNDG-WGDMKGIYSKLDYIKELGADAIWISPFYDSPQDDMGYDIANYEKVWPTYGTNEDCFKVIEKTHKLGMKFITDLVINHCSSEHEWFKESRSSKTNPKRDWFFWRPPKGYDKN-GAPIPPNNWKSYFGGSAWTFDEKTQEFYLRLFASTQPDLNWESEECRKAIYESSVGFWLDHGVDGFRIDVGSLYSKVPGLPDAPIVDKDSEWQSSDPLTLNGPRIHEFHQEMNKFMRDRVK-DGREIMTVGEMQHAPN-EVKKMYTSASRHELGELFNFSHTDVGTSPLFRYNLVPAVLKDFKVSLAELFEYI------NGTDCWSTVYLENHDQPRSITRFGDD-SPK-YRVVSGKMLSVLLTALTGTLYIYQGQELGQINF-KNWPVEKYEDVEIRNNFRVIKEEHGEN---SVQMKKFLEAVALISRDHARTPMQWS---GEEPNAGFSG---PDAKPWFYLNESFREGINVETEEKDPDSVLNFWKKALKFRKEHKDIAVYGYDFEFV-DLENKKLFSFTKKYGK----KTMFTTLNFSSDEVDFEFPND-VSYSLAFGNYDEGQVDASSKTLKPWEGRIYINESA--"

# s_paradoxus_CBS432 = "MTISD----HPETEKKWWKEATIYQIYPASF----------KDSNNDG-WGDLKGITSKLPYIKDLGVDAIW VCPFYDSPQQDMGYDISNYEKVWPTYGTNEDCFELIDKTHKLGMKFITDLVINHCSTEHEWFKESRSSKTNP KRDWFFWRPPKGYDDE-GKPIPPNNWKSFFGGSAWTFDEKTQEFYLRLFASRQADLNWENEDCRKAIYESAV GFWLDHGVDGFRIDTAGLYSKRPGLPDSPIFDKTSKLQHPNWGSHNGPKIHEYHQELHKFMKNRVK-DGREI MTVGEVAHGSD-NA--LYTSAARYEISEVFSFTHVDIGTSPFFRYNIVPFSLKQWKEAIASNFLFI------ NGTDSWATTYIENHDQPRSITRFADD-SPK-YCTTSGKLLALLECSLTGTLYVYQGQEIGQINF-KDWPIEK YEDVDVRNNHEIIRKKFGED---SMEMQDFLRGIALLSRDHSRTPMPWT---KEKPNAGFTG---PDAKPWF FLNESFQQGINVEQESENNDSVLNFWRRALQARKKYKDLMIYGYDFQFI-DLDSDQIFSFTKEYED----KT LFAALNFSGEEIEFNLPREGASLSFIFGNY--DDTDASSRVLKPWEGRLYLVK----"

# S_cerevisiae_YIIc17_E5 = "MTISD----HPETEPKWWKEATIYQIYPASF----------KDSNNDG-WGDLKGITSKLQYIKDLGVDAIW VCPFYDSPQQDMGYDISNYEKVWPTYGTNEDCFELIDKTHKLGMKFITDLVINHCSTEHEWFKESRSSKTNP KRDWFFWRPPKGYDAE-GKPIPPNNWKSFFGGSAWTFDETTNEFYLRLFASRQVDLNWENEDCRRAIFESAV GFWLDHGVDGFRIDTAGLYSKRPGLPDSPIFDKTSKLQHPNWGSHNGPRIHEYHQELHRFMKNRVK-DGREI MTVGEVAHGSD-NA--LYTSAARYEVSEVFSFTHVELGTSPFFRYNIVPFTLKQWKEAIASNFLFI------ NGTDSWATTYIENHDQARSITRFADD-SPK-YRKISGKLLTLLECSLTGTLYVYQGQEIGQINF-KEWPIEK YEDVDVKNNYEIIKKSFGKN---SKEMKDFFKGIALLSRDHSRTPMPWT---KDKPSAGFTG---PDVKPWF FLNESFEQGINVEQESRDDDSVLNFWKRALQARKKYKELMIYGYDFQFI-DLDSDQIFSFTKEYED----KT LFAALNFSGEEIEFSLPREGASLSFILGNY--DDTDVSSRVLKPWEGRIYLVK----"

# S_cerevisiae_S288c_IMA1 = "".join([
# "MTISSA---HPETEPKWWKEATFYQIYPASF----------KDSNDDG-WGDMKGIASKLEYIKELGADAIW",
# "ISPFYDSPQDDMGYDIANYEKVWPTYGTNEDCFALIEKTHKLGMKFITDLVINHCSSEHEWFKESRSSKTNP",
# "KRDWFFWRPPKGYDAE-GKPIPPNNWKSYFGGSAWTFDEKTQEFYLRLFCSTQPDLNWENEDCRKAIYESAV",
# "GYWLDHGVDGFRIDVGSLYSKVVGLPDAPVVDKNSTWQSSDPYTLNGPRIHEFHQEMNQFIRNRVK-DGREI",
# "MTVGEMQHASD-ETKRLYTSASRHELSELFNFSHTDVGTSPLFRYNLVPFELKDWKIALAELFRYI------",
# "NGTDCWSTIYLENHDQPRSITRFGDD-SPK-NRVISGKLLSVLLSALTGTLYVYQGQELGQINF-KNWPVEK",
# "YEDVEIRNNYNAIKEEHGEN---SEEMKKFLEAIALISRDHARTPMQWS---REEPNAGFSG---PSAKPWF",
# "YLNDSFREGINVEDEIKDPNSVLNFWKEALKFRKAHKDITVYGYDFEFI-DLDNKKLFSFTKKYNN----KT",
# "LFAALNFSSDATDFKIPNDDSSFKLEFGNYPKKEVDASSRTLKPWEGRIYISE----"
# ])

# def exercise_9(seq):
#   # data 3 from voordeckers
#   # >K.thermotolerans GI:255711056
#   # this code print: YVGSLMQDE
#   for a in voordeckers:
#     print(seq[a-1], end="")

# def exercise_9_around(seq):
#   # data 3 from voordeckers
#   # >K.thermotolerans GI:255711056
#   # this code print: YVGSLMQDE
#   for a in voordeckers:
#     print(a)
#     print(seq[a-5:a+5])


# # print(s)
# mine = "\
# ---MTISSAHPETEPKWWKEATIYQIYPASFKDSN-----------NDGWGDLKGIASKLEYIKELGVDAIWICPFYDSPQDDMGYDIANYEKVWPTYGTNEDCFALIEKTHKLGMKFITDLVINHCSSEHEWFKESRSSKTNPKRDWFFWRPPKGYDAEGKPIPPNNWRSFFGGSAWTFDEKTQEFYLRLFASTQPDLNWENEDCRKAIYESAVGYWLDHGVDGFRIDVGSLYSKVPGLPDAPVTDENSKWQHSDPFTMNGPRIHEFHQEMNKFMRNRV-KDGREIMTVGEVQHGSDETKRLYTSASRHELSELFNFSHTDVGTSPKFRYNLVPFELKDWKVALAELFRFINGTDCWSTIYLENHDQPRSITRFGDDSPKNRVISGKLLSVLLVSLTGTLYVYQGQELGQINF-KNWPIEKYEDVEVRNNYKAIKEEHGENSK---EMKKFLEGIALISRDHARTPMPWTKEEPNAGFSG---PDAKPWFYLNESFREGINAEDESKDPNSVLNFWKEALQFRKAHKDITVYGYDFEFIDLDNKKLFSFTKK--Y-DNKTLFAALNFSSDEIDFTIPNDSASFKLEFGNYPDKEVDASSRTLKPWEGRIYISE--"


# # exercise_9(S_cerevisiae_S288c_IMA1)
# print(mine)
# exercise_9_around(mine)